directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    UnusedParameters:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
    ControlParameter:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "db/migrate":
    IrresponsibleModule:
      enabled: false
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
  "config":
    IrresponsibleModule:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
